name       : pueue
version    : 0.12.2
release    : 6
source     :
    - https://github.com/Nukesor/pueue/archive/refs/tags/v0.12.2.tar.gz : 3acd923759d5731b69a9a4a16c83c16a1f33589767da2ab7eb0cbe49ea06eabd
license    : MIT
component  : system.utils
networking : yes
summary    : A command-line task management tool for sequential and parallel execution of long-running tasks
description: |
    Pueue is a command-line task management tool for sequential and parallel execution of long-running tasks. Simply put, it's a tool that processes a queue of shell commands. On top of that, there are a lot of convenience features and abstractions. Since Pueue is not bound to any terminal, you can control your tasks from any terminal on the same machine. The queue will be continuously processed, even if you no longer have any active ssh sessions.
builddeps  :
    - cargo
build      : |
    cargo build --release
    ./build_completions.sh
install    : |
    install -Dm00755 target/release/pueue $installdir/usr/bin/pueue
    install -Dm00755 target/release/pueued $installdir/usr/bin/pueued
    install -Dm00644 utils/pueued.service $installdir/%libdir%/systemd/user/pueued.service
    install -Dm00644 utils/completions/pueue.bash $installdir/usr/share/bash-completion/completions/pueue
    install -Dm00644 utils/completions/_pueue $installdir/usr/share/zsh/site-functions/_pueue
    install -Dm00644 utils/completions/pueue.fish $installdir/usr/share/fish/vendor_completions.d/pueue.fish
check      : |
    cargo test --all
